= context.yml
:toc:

You can have as many context as you want in your technology folder.
A good approch is to have subfolders for each context.

.Folder hierarchy example
----
📂 example-technology
  📂 1.0-gce
    📄 context.yml
  📂 1.0-aws
    📄 context.yml
  📄 technology.yml
----

.Folder hierarchy example
----
📂 example-technology
  📂 gce
    📂 1.0
      📄 context.yml
    📂 1.1
      📄 context.yml
  📄 technology.yml
----

== Configuration

=== `id`

#SUGGESTION: rename to `name`#

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|Yes
|-
|===

The unique identifier of the context in your technology.

=== `label`

#SUGGESTION: rename to `displayName`#

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|Will take the `id` if not provided
|===

The name of the context displayed in the User Interface.

=== `description`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string` (multiline)
|No
|-
|===

The description of the context displayed in the User Interface.

[source,yml]
----
description: >
  Several lines of text,
  with some "quotes" of various 'types',
  plus another line at the end.
----

=== `available`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`boolean`
|No
|`true`
|===

Set to `false` to prevent Saagie from displaying the context to the users.

=== `recommended`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`boolean`
|No
|`false`
|===

Set to `true` to recommend this context to the users.

=== `trustLevel`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`: `stable` \| `experimental`
|No
|-
|===

Set to `experimental` to warn the user that the context is not stable.

=== `endpoint`

Configuration for the endpoint creation form.
This form allows the user to create one or more endpoint connection for this technology context.

.example
[source,yml]
----
endpoint:
  checkConnection:
    script: ./src/checkConnection.js
    function: checkConnection
  features:
    - type: URL
      name: url
      label: Endpoint URL
      required: true
      helper: E.g. https://amazingtech.company.com/api/v1
----


==== `endpoint.checkConnection`

Provide a method to check the status of the endpoint connection.

==== `endpoint.checkConnection.script`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|-
|===

Relative path to JavaScript file where there is a function to check the status of the endpoint connection.

==== `endpoint.checkConnection.function`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|`default`
|===

The name of the exported function to execute when the check endpoint connection action is called. If no `function` name is provided, the default export of the `script` will be used.

==== `endpoint.features`

List of available link:features.adoc[features] in the endpoint creation form.


=== `job`

Configuration for the job creation form.
This form allows the user to create one or more job for this technology context.

==== `job.features`

List of available link:features.adoc[features] in the job creation form.

=== `instance`

Configuration for the job instances.

==== `instance.actions`

Configuration for each instance action.

==== `instance.actions.onStart`

Provide a method to start the job.

==== `instance.actions.onStart.script`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|Yes
|-
|===

Relative path to JavaScript file where there is a function to start the job.

==== `instance.actions.onStart.function`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|`default`
|===

The name of the exported function to execute when the start job action is called. If no `function` name is provided, the default export of the `script` will be used.

==== `instance.actions.onStop`

Provide a method to stop the job.

==== `instance.actions.onStop.script`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|-
|===

Relative path to JavaScript file where there is a function to stop the job.

==== `instance.actions.onStop.function`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|`default`
|===

The name of the exported function to execute when the stop job action is called. If no `function` name is provided, the default export of the `script` will be used.

==== `instance.actions.getStatus`

Provide a method to get the job status.

==== `instance.actions.getStatus.script`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|Yes
|-
|===

Relative path to JavaScript file where there is a function to get the job status.

==== `instance.actions.getStatus.function`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|`default`
|===

The name of the exported function to execute when the get job status action is called. If no `function` name is provided, the default export of the `script` will be used.

==== `instance.actions.getLogs`

Provide a method to get the job logs.

==== `instance.actions.getLogs.script`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|-
|===

Relative path to JavaScript file where there is a function to get the job logs.

==== `instance.actions.getLogs.function`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|`default`
|===

The name of the exported function to execute when the get job logs action is called. If no `function` name is provided, the default export of the `script` will be used.

== Example

[source,yml]
----
id: aws-10.0
label: AWS v10.0
description: Techno v10 on AWS
available: true
recommended: false
trustLevel: stable

endpoint:
  checkConnection:
    script: ./src/checkConnection.js
    function: checkConnection
  features:
    - type: URL
      name: url
      label: Endpoint URL
      required: true
      helper: E.g. https://amazingtech.company.com/api/v1

    - type: TEXT
      name: login
      label: Login

    - type: PASSWORD
      name: password
      label: Password

job:
  features:
    - type: ENDPOINTS
      name: endpoint
      label: Endpoint
      required: true

    - type: SELECT
      name: dataset
      label: Dataset
      required: true
      options:
        script: ./src/entityForm.js
        function: getDatasets
      dependsOn:
        - endpoint

    - type: SELECT
      name: project
      label: Project
      required: true
      options:
        script: ./src/entityForm.js
        function: getProjects
      dependsOn:
        - dataset

    - type: SELECT
      name: process
      label: Process
      required: true
      options:
        script: ./src/entityForm.js
        function: getProcesses
      dependsOn:
        - project

instance:
  actions:
    onStart:
      script: ./src/entityActions.js
      function: start
    onStop:
      script: ./src/entityActions.js
      function: stop
    getStatus:
      script: ./src/entityActions.js
      function: getStatus
    getLogs:
      script: ./src/entityActions.js
      function: getLogs
----