= entityActions.js
:toc:

The entityAction.js file should export the `start`, `stop`, `getStatus` and `getLogs` methods that will allow one to orchestrate a job.
It should be located in a `src` folder like so:

.Folder hierarchy example
----
📂 example-technology
  📂 1.0-gce
    📂 src
      📄 entityActions.js
  📂 1.0-aws
    📂 src
      📄 entityActions.js
----


=== start(jobParams)
The `start` method should contain the code that will run the job. It should return a success or an error, using the custom `Response` object implemented in the `sdk-extech` library.

This method should be called with one argument `jobParams`, holding the information about the job (name, id, features...).

|===
| ARGUMENTS | TYPE | DEFAULT VALUE

|`jobParams`
|`object`
|-
|===

Example:

[source,javascript]
----
const axios = require('axios');
const { Response } = require('@saagie/sdk');

exports.start = async (jobParams) => {
  const { name, features } = jobParams;

  try {
    // Make a fetch request to start the job using axios
    await axios.get(`${features.endpoint.url}/datasets/${features.dataset.id}/projects/${features.project.id}/processes/${features.process.id}/run`);

    // And return the response
    return Response.success();
  }

  catch (error) {
    // Handle the error
    return Response.error(`Fail to start job "${name}"`, { error })
  }
}
----

=== stop(jobParams)

The `stop` method contains the code that will stop a running job. It should return a success or an error, using the custom `Response` object implemented in the `sdk-extech` library.

This method should be called with one argument `jobParams`, holding the information about the job (name, id, features...).

|===
| ARGUMENTS | TYPE | DEFAULT VALUE

|`jobParams`
|`object`
|-
|===

Example:

[source,javascript]
----
exports.stop = async (jobParams) => {
  const { name, features } = jobParams;

  try {
    // Make a fetch request to stop the job
    await axios.get(`${features.endpoint.url}/datasets/${features.dataset.id}/projects/${features.project.id}/processes/${features.process.id}/stop`);

    // And return the response
    return Response.success();
  }

  catch (error) {
    // Handle the error
    return Response.error(`Fail to stop job "${name}"`, { error })
  }
}
----

=== getStatus(jobParams)

The `getStatus` method contains the code that will get the current status of a job. It should return a success with the current job status, or an error, using the custom `Response` object implemented in the `sdk-extech` library.

`getStatus` should be called with one argument jobParams holding the information about the job (name, id, features...).

|===
| ARGUMENTS | TYPE | DEFAULT VALUE

|`jobParams`
|`object`
|-
|===

Example:

[source,javascript]
----
exports.getStatus = async (jobParams) => {
  const { name, features } = jobParams;

  try {
    // Make a fetch request to get the current status of the job
    const status = await axios.get(`${features.endpoint.url}/datasets/${features.dataset.id}/projects/${features.project.id}/processes/${features.process.id}/getStatus`);

    // And return the response along with the current status of the job
    return Response.success(status);
  }

  catch (error) {
    // Handle the error
    return Response.error(`Fail to get the status of job "${name}"`, { error })
  }
}
----

=== getLogs(jobParams)

The `getLogs` method contains the code that will get the logs of a running job. It should return a success with the current job logs, or an error, using the custom `Response` object implemented in the `sdk-extech` library.

`getLogs` should be called with one argument jobParams holding the information about the job (name, id, features...).

|===
| ARGUMENTS | TYPE | DEFAULT VALUE

|`jobParams`
|`object`
|-
|===

Example:

[source,javascript]
----
exports.getLogs = async (jobParams) => {
  const { name, features } = jobParams;

  try {
    // Make a fetch request to get the logs of the job
    const logs = await axios.get(`${features.endpoint.url}/datasets/${features.dataset.id}/projects/${features.project.id}/processes/${features.process.id}/getLogs`);

    // And return the response along with the logs of the job
    return Response.success({ logs });
  }

  catch (error) {
    // Handle the error
    return Response.error(`Fail to get logs of job "${name}"`, { error })
  }
}
----

For more info on the `jobParams` object see the link:jobParams.adoc[jobParams] page.