= `features`
:toc:

Think of features as a composable fields.

== Available feature types

=== `URL`

Using `URL` type, the user will have a field with URL type validation.

All the <<Shared configurations,shared configurations>> are available for this feature.

.URL Feature
[source,yaml]
----
- type: URL
  name: url
  label: Endpoint URL
  required: true
  helper: E.g. https://amazingtech.company.com/api/v1
  dependsOn:
    - dependency-name
----

=== `TEXT`

Using `TEXT` type, the user will be free to give any value they want.

.TEXT Feature
[source,yaml]
----
- type: TEXT
  name: login
  label: Login
  required: true
  helper: E.g. This is a text
  dependsOn:
    - dependency-name
----

=== `PASSWORD`

Using `PASSWORD` type, the user will have a field with password type validation.

.PASSWORD Feature
[source,yaml]
----
- type: PASSWORD
  name: password
  label: Password
  required: true
  helper: Please provide a password
  dependsOn:
    - dependency-name
----

=== `ENDPOINT`

Using `ENDPOINT` type, the user will have a select box with the available endpoints previously created.

.ENDPOINT Feature
[source,yaml]
----
- type: ENDPOINT
  name: endpoint
  label: Endpoint
  required: true
  helper: Please select the endpoint to use
  dependsOn:
    - dependency-name
----

=== `SELECT`

Using `SELECT` type, the user will be able to select a value in a list of options.
This list can be hard-coded or dynamically loaded using scripts.

.SELECT Feature
[source,yaml]
----
# Using script
- type: SELECT
  name: dataset
  label: Dataset
  required: true
  options:
    script: ./src/script.js
    function: getDatasets
  dependsOn:
    - endpoint

# Using hard coded values
- type: SELECT
  name: dataset-hard-coded
  label: Dataset Hard Coded
  required: true
  options:
    - id: first
      label: First
    - id: second
      label: Second
    - id: third
      label: Third
  dependsOn:
    - endpoint
----

==== `options`

===== Hard Coded Options

Hard coded options can be provided using an array made of `id` and `label`. The `label` is what the user will see on the User Interface.

[source,yaml]
----
- type: SELECT
  name: project
  options:
    - id: first
      label: First
    - id: second
      label: Second
    - id: third
      label: Third
----

===== Dynamic Options

Dynamic options system provide a way to call a web service to get the options.
Use `script` and `function` keys to provide path to a script and a function to call.

[source,yaml]
----
- type: SELECT
  name: project
  options:
    script: ./entityForm.js
    function: getProjects
----

Check the scripts documentation for more information. #TODO ADD LINK TO DEDICATED DOCUMENTATION#

== Shared configurations

Each feature has multiple configuration keys. Most of the keys are basic, the complicated one being `type`.

=== `type`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string` see <<Available feature types>>
|Yes
|-
|===

=== `name`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|Yes
|-
|===

The feature name should be unique in the context.

=== `label`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|Will take the `name` if not provided.
|===

The label of the feature displayed in the User Interface.

=== `helper`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`string`
|No
|-
|===

The helper displayed on the User Interface to clarify the feature.

=== `required`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`boolean`
|No
|false
|===

The requirement of the feature.

=== `dependsOn`

|===
| TYPE | REQUIRED | DEFAULT VALUE

|`array`
|No
|-
|===

Identifies any feature that must be successfully filled before this feature shows up in the User Interface.

[source,yaml]
----
- type: TEXT
  name: login

- type: PASSWORD
  name: password
  dependsOn:
    - login
----

== Example

.context.yaml 
[source,yaml]
----
# [...]
endpoint:
  features:
    - type: URL
      name: url
      label: Endpoint URL
      required: true
      helper: E.g. https://amazingtech.company.com/api/v1

    - type: TEXT
      name: login
      label: Login

    - type: PASSWORD
      name: password
      label: Password

job:
  features:
    - type: ENDPOINT
      name: endpoint
      label: Endpoint
      required: true

    - type: SELECT
      name: dataset
      label: Dataset
      required: true
      options:
        script: ./src/entityForm.js
        function: getDatasets
      dependsOn:
        - connection

    - type: SELECT
      name: project
      label: Project
      required: true
      options:
        script: ./src/entityForm.js
        function: getProjects
      dependsOn:
        - dataset

    - type: SELECT
      name: process
      label: Process
      required: true
      options:
        script: ./src/entityForm.js
        function: getProcesses
      dependsOn:
        - project
# [...]
----