name: Pull Requests Checks

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: |
          yarn install
          yarn bs
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
